[server]
socket_path = "~/.sello/sello.sock"
timeout_secs = 30

[keys]
directory = "~/.sello/keys"
default_key = "default"

[policy]
whitelist_enabled = false
whitelist = []
blacklist = []

[policy.transaction_limits]
# ETH = "1000000000000000000"  # 1 ETH

[policy.daily_limits]
# ETH = "10000000000000000000"  # 10 ETH
