[server]
socket_path = "~/.txgate/txgate.sock"
timeout_secs = 30
# Allow reading passphrases from TXGATE_PASSPHRASE env var.
# Enables autonomous/headless signing. Use with caution.
# allow_env_passphrase = false

[keys]
directory = "~/.txgate/keys"
default_key = "default"

[policy]
whitelist_enabled = false
whitelist = []
blacklist = []

[policy.transaction_limits]
# ETH = "1000000000000000000"  # 1 ETH
